version: '3.3'

services:
  mysql:
    image: mysql:5
    ports:
      - "33061:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: LbRootPass1
      MYSQL_DATABASE: lbcat
      MYSQL_USER: lbuser
      MYSQL_PASSWORD: LiquibasePass1
    volumes:
      - "./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql"

  postgres-9:
    image: postgres:9
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: LbRootPass1
      POSTGRES_DB: lbcat
    volumes:
      - "./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"

  postgres-10:
    image: postgres:10
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: LbRootPass1
      POSTGRES_DB: lbcat
    volumes:
      - "./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"

  postgres-11:
    image: postgres:11
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: LbRootPass1
      POSTGRES_DB: lbcat
    volumes:
      - "./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"

  postgres-latest:
    image: postgres:latest
    ports:
      - "5435:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: LbRootPass1
      POSTGRES_DB: lbcat
    volumes:
      - "./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: LiquibasePass1
    volumes:
      - "./mssql-init.sh:/docker-entrypoint-initdb.d/mssql-init.sh"
      - "./mssql-init.sql:/docker-entrypoint-initdb.d/mssql-init.sql"
    entrypoint: /bin/bash /docker-entrypoint-initdb.d/mssql-init.sh
